checks:
  javascript: true
build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - command: "npm --prefix src/lambdaa install && ls && npm --prefix src/lambdaa run test"
            coverage:
              file: ./src/lambdaa/coveragee/lcov.info
              format: lcov
  environment:
    node: "v14.21.3"
